sbatch cc_6_marginal_geo_it_AMZ.sh
sbatch cc_6_marginal_geo_itpa_AMZ.sh
sbatch cc_6_marginal_geo_pa_AMZ.sh
sbatch cc_6_marginal_ten_areas_full_all_AMZ.sh
sbatch cc_6_marginal_ten_areas_full_ov_AMZ.sh
sbatch cc_6_marginal_ten_areas_it_AMZ.sh
sbatch cc_6_marginal_ten_areas_pa_AMZ.sh
# sbatch cc_6_marginal_ten_it_all_AMZ.sh
# sbatch cc_6_marginal_ten_it_ov_AMZ.sh
sbatch cc_6_marginal_ten_itpa_AMZ.sh
# sbatch cc_6_marginal_ten_pa_all_AMZ.sh
# sbatch cc_6_marginal_ten_pa_ov_AMZ.sh
